version: "3.8"
services:
  app:
    container_name: wellness-events
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - 3002:3002
    volumes:
      - ./:/home/app
