import {
  MSG_DELETE_SUCCESS,
  MSG_FAILED_FETCH,
  MSG_STORE_SUCCESS,
  MSG_EDIT_SUCCESS,
  MSG_UPDATE_SUCCESS,
  MSG_STORE_FAILED,
  MSG_DELETE_FAILED,
  MSG_UPDATE_FAILED,
  MSG_CONFIRM_DELETE,
} from "./messages";
export {
  MSG_FAILED_FETCH,
  MSG_CONFIRM_DELETE,
  MSG_STORE_SUCCESS,
  MSG_DELETE_SUCCESS,
  MSG_EDIT_SUCCESS,
  MSG_UPDATE_SUCCESS,
  MSG_STORE_FAILED,
  MSG_DELETE_FAILED,
  MSG_UPDATE_FAILED,
};
